A = str(input())
A = str.split(A)
B = float(A[1])
C = float(A[2])
A = float(A[0])
print('TRIANGULO: {:.3f}'.format((A*C)/2))
print('CIRCULO: {:.3f}'.format((C*C*(3.14159))))
print('TRAPEZIO: {:.3f}'.format(((A+B)/2)*C))
print('QUADRADO: {:.3f}'.format(B**2))
print('RETANGULO: {:.3f}'.format(A*B))
